name: "Build"
on:
  push:
    tags:
      - "*"
    branches:
      - "master"
      - "develop"
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC
          format: 'YYYY-MM-DD-HH-mm-ss'

      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .
          filename: "{name}-{version}-${{ steps.time.outputs.time }}.xpi"
          ignoreFiles: '[ "package.json","package-lock.json","yarn.lock" ]'

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.JWT_ISSUER }}
          apiSecret: ${{ secrets.JWT_SECRET }}
          timeout: 900000
      - name: "Create Release"
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: ${{ steps.web-ext-build.outputs.target }}
          makeLatest: "true"
          body:
            "# !! AUTOMATED RELEASE!! \n
            These aren't tested.\nThe extension is built from the source code from the master branch so you can check it out yourself."
          name: "git-${{ steps.time.outputs.time }}"
  
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: rocks.realfx.spaceheydarkmode-${{ steps.time.outputs.time }}.xpi
          path: ${{ steps.web-ext-build.outputs.target }}
